apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-ha
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-ha
  template:
    metadata:
      labels:
        app: php-ha
    spec:
      containers:
        - name: php
          image: php-ha:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: php-db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: php-ha-nodeport
spec:
  type: NodePort
  selector:
    app: php-ha
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
